# Generated by Django 4.2.5 on 2023-09-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scheduling',
            new_name='Schedules',
        ),
    ]
