# Generated by Django 4.2.5 on 2023-09-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_scheduling_schedules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedules',
            new_name='Scheduling',
        ),
    ]
